version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
  api:
    build:
      dockerfile: ./dockerfile
    ports:
      - 3000:3000